# Generated by Django 5.0.6 on 2025-02-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaProceso', models.DateTimeField()),
                ('CodigoBarra', models.CharField(max_length=50)),
                ('Lote', models.IntegerField()),
                ('Area', models.CharField(max_length=100)),
                ('DestinoProducto', models.CharField(max_length=100)),
                ('TotalKilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Corte', models.CharField(max_length=100)),
                ('Calidad', models.CharField(max_length=50)),
                ('Conservacion', models.CharField(max_length=50)),
                ('FechaProduccion', models.DateField()),
                ('TotalBandejas', models.IntegerField(blank=True, null=True)),
                ('DiaProceso2', models.DateField()),
                ('HoraProceso', models.IntegerField()),
                ('HoraIntervalo', models.CharField(max_length=20)),
                ('Turno', models.CharField(max_length=20)),
                ('MesProceso', models.IntegerField()),
            ],
        ),
    ]
