# Generated by Django 5.0.6 on 2025-06-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargarArchivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cargar_archivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nom_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_etiqueta', models.AutoField(db_column='id_etiqueta', primary_key=True, serialize=False)),
                ('DiaProceso', models.DateField(db_column='dia_proceso')),
                ('CodigoBarra', models.CharField(db_column='codigo_barra', max_length=50)),
                ('Lote', models.CharField(db_column='lote', max_length=50)),
                ('Area', models.CharField(db_column='area', max_length=50)),
                ('DestinoProducto', models.CharField(db_column='destino_producto', max_length=100)),
                ('TotalKilos', models.DecimalField(db_column='total_kilos', decimal_places=2, max_digits=10)),
                ('TotalBandejas', models.IntegerField(db_column='total_bandejas')),
                ('Corte', models.CharField(blank=True, db_column='corte', max_length=50, null=True)),
                ('Calidad', models.CharField(blank=True, db_column='calidad', max_length=50, null=True)),
                ('Conservacion', models.CharField(blank=True, db_column='conservacion', max_length=50, null=True)),
                ('HoraProceso', models.TimeField(db_column='hora_proceso')),
                ('HoraIntervalo', models.CharField(db_column='hora_intervalo', max_length=20)),
                ('Turno', models.CharField(db_column='turno', max_length=20)),
                ('MesProceso', models.CharField(db_column='mes_proceso', max_length=20)),
                ('FechaProduccion', models.DateField(db_column='fecha_produccion')),
                ('DiaProceso2', models.DateField(db_column='dia_proceso2')),
                ('archivo_origen', models.ForeignKey(blank=True, db_column='id_archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiquetas.cargararchivo')),
            ],
            options={
                'db_table': 'etiquetas_tunel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_user', models.CharField(max_length=100)),
                ('apellido_user', models.CharField(max_length=100)),
                ('email_user', models.EmailField(max_length=254, unique=True)),
                ('pass_user', models.CharField(max_length=255)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='etiquetas.roluser')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cargararchivo',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='etiquetas.usuario'),
        ),
    ]
