# Generated by Django 5.0.6 on 2025-02-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0002_reporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
