# Generated by Django 5.0.6 on 2025-02-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0004_reporteguardado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteGuardado',
        ),
    ]
