# Generated by Django 5.0.6 on 2025-02-21 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0006_reporteguardado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReporteGuardado',
            new_name='Reporte',
        ),
    ]
