# Generated by Django 5.0.6 on 2025-02-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0009_historialreporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='HistorialReporte',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
