# Generated by Django 5.0.6 on 2025-05-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0010_remove_reporte_usuario_delete_historialreporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('digitador', 'Digitador'), ('camarero', 'Camarero'), ('asistente', 'Asistente'), ('admin', 'Administrador'), ('superusuario', 'Superusuario')], max_length=15)),
                ('estado', models.CharField(default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaSalidaTunel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_produccion', models.DateField()),
                ('codigo_barra', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('destino_producto', models.CharField(max_length=100)),
                ('total_kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bandejas', models.IntegerField()),
                ('corte', models.CharField(blank=True, max_length=50, null=True)),
                ('calidad', models.CharField(blank=True, max_length=50, null=True)),
                ('conservacion', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_proceso', models.TimeField()),
                ('hora_intervalo', models.CharField(blank=True, max_length=20, null=True)),
                ('turno', models.CharField(max_length=20)),
                ('mes_proceso', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['dia_produccion'],
                'unique_together': {('codigo_barra', 'dia_produccion', 'hora_proceso')},
            },
        ),
    ]
