# Generated by Django 5.0.6 on 2025-05-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0011_usuario_etiquetasalidatunel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtiquetaSalidaTunel',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
